/**
 * Aggregators and cumulative formatters.
 *
 * An aggregator processes an array and returns a single value. The array is selected in the template with empty
 * brackets: `{d.items[].price:aggSum}`. Carbone rewrites this marker into `{d.items:_pluck('price'):aggSum}`
 * (see parser.expandAggregatorMarkers), so aggregators can also be used inside loops: `{d.cars[i].wheels[].size:aggSum}`.
 *
 * Cumulative formatters are used inside a loop, and accumulate values row after row: `{d.items[i].price:cumSum}`.
 */

const hasOwn = Object.prototype.hasOwnProperty;

/**
 * Get all the values of an attribute path, inside an array of objects
 * Segments finishing with `[]` are arrays which are flattened: `wheels[].size`
 *
 * @private
 * @param {Mixed}   value     current value
 * @param {Array}   segments  path, split by "."
 * @param {Integer} index     current segment
 * @param {Array}   out       (modified) all found values. A missing attribute gives `undefined`
 */
function _collect (value, segments, index, out) {
  if (index === segments.length) {
    out.push(value);
    return;
  }
  var _segment = segments[index];
  var _isArray = _segment.endsWith('[]');
  var _name    = _isArray ? _segment.slice(0, -2) : _segment;
  var _next    = (value !== null && typeof value === 'object' && hasOwn.call(value, _name)) ? value[_name] : undefined;
  if (_isArray === true) {
    if (_next instanceof Array) {
      for (var i = 0; i < _next.length; i++) {
        _collect(_next[i], segments, index + 1, out);
      }
    }
    return;
  }
  _collect(_next, segments, index + 1, out);
}

/**
 * Internal formatter, generated by Carbone when a marker contains empty brackets `[]` followed by an aggregator.
 * It extracts an attribute of each item of an array.
 *
 * @private
 * @param  {Array}  d     array of items
 * @param  {String} path  [optional] attribute path of each item. If empty, items are returned
 * @return {Array}        array of values. It is empty if `d` is not an array
 */
function _pluck (d, path) {
  if (d instanceof Array === false) {
    return [];
  }
  if (!path) {
    return d.slice();
  }
  var _segments = (path + '').split('.');
  var _out = [];
  for (var i = 0; i < d.length; i++) {
    _collect(d[i], _segments, 0, _out);
  }
  return _out;
}

function _toNumber (value) {
  if (value === null || typeof value === 'undefined' || typeof value === 'boolean') {
    return null;
  }
  var _number = parseFloat(value);
  return Number.isNaN(_number) === true ? null : _number;
}

function _numbers (d) {
  var _res = [];
  for (var i = 0; i < d.length; i++) {
    var _number = _toNumber(d[i]);
    if (_number !== null) {
      _res.push(_number);
    }
  }
  return _res;
}

// key used to find distinct values. 1 and "1" are distinct
function _key (value) {
  return typeof value + ':' + (value !== null && typeof value === 'object' ? JSON.stringify(value) : value);
}

function _distinct (d) {
  var _seen = new Set();
  var _res = [];
  for (var i = 0; i < d.length; i++) {
    if (d[i] === null || typeof d[i] === 'undefined') {
      continue;
    }
    var _k = _key(d[i]);
    if (_seen.has(_k) === false) {
      _seen.add(_k);
      _res.push(d[i]);
    }
  }
  return _res;
}

function _separator (separator) {
  if (separator === undefined || separator === null) {
    return ', ';
  }
  return (separator + '').replace(/\\r\\n/g, '\r\n').replace(/\\n/g, '\n');
}

/**
 * Sum of all numeric values of an array. Values which are not numbers (null, text, ...) are ignored. It returns 0 if there is no value.
 *
 * @version 3.5.7 new
 *
 * @example [[10, 20.5, 5]]
 * @example [[10, null, "abc", "5"]]
 * @example [[]]
 *
 * @param  {Array}  d  array of values. In a template: `{d.items[].price:aggSum}`
 * @return {Number}    sum
 */
function aggSum (d) {
  if (d instanceof Array === false) {
    return d;
  }
  return _numbers(d).reduce(function (sum, n) {
    return sum + n;
  }, 0);
}

/**
 * Average of all numeric values of an array. Values which are not numbers are ignored. It returns an empty value if there is no number.
 *
 * @version 3.5.7 new
 *
 * @example [[10, 20, 30]]
 * @example [[10, null, "abc", "20"]]
 * @example [[]]
 *
 * @param  {Array}  d  array of values. In a template: `{d.items[].price:aggAvg}`
 * @return {Number}    average
 */
function aggAvg (d) {
  if (d instanceof Array === false) {
    return d;
  }
  var _values = _numbers(d);
  if (_values.length === 0) {
    return null;
  }
  return aggSum(_values) / _values.length;
}

/**
 * Smallest numeric value of an array. Values which are not numbers are ignored. It returns an empty value if there is no number.
 *
 * @version 3.5.7 new
 *
 * @example [[10, 3, 20]]
 * @example [[-5, null, "abc", "2"]]
 * @example [[]]
 *
 * @param  {Array}  d  array of values. In a template: `{d.items[].price:aggMin}`
 * @return {Number}    minimum
 */
function aggMin (d) {
  if (d instanceof Array === false) {
    return d;
  }
  var _values = _numbers(d);
  return _values.length === 0 ? null : Math.min.apply(null, _values);
}

/**
 * Highest numeric value of an array. Values which are not numbers are ignored. It returns an empty value if there is no number.
 *
 * @version 3.5.7 new
 *
 * @example [[10, 3, 20]]
 * @example [[-5, null, "abc", "2"]]
 * @example [[]]
 *
 * @param  {Array}  d  array of values. In a template: `{d.items[].price:aggMax}`
 * @return {Number}    maximum
 */
function aggMax (d) {
  if (d instanceof Array === false) {
    return d;
  }
  var _values = _numbers(d);
  return _values.length === 0 ? null : Math.max.apply(null, _values);
}

/**
 * Number of items of an array.
 *
 * @version 3.5.7 new
 *
 * @example [[10, 3, 20]]
 * @example [["a", "a", null]]
 * @example [[]]
 *
 * @param  {Array}   d  array of values. In a template: `{d.items[]:aggCount}`
 * @return {Integer}    number of items
 */
function aggCount (d) {
  if (d instanceof Array === false) {
    return d;
  }
  return d.length;
}

/**
 * Number of distinct values of an array. null and undefined are ignored.
 *
 * @version 3.5.7 new
 *
 * @example [["a", "b", "a"]]
 * @example [[1, "1", 1, null]]
 * @example [[]]
 *
 * @param  {Array}   d  array of values. In a template: `{d.items[].type:aggCountD}`
 * @return {Integer}    number of distinct values
 */
function aggCountD (d) {
  if (d instanceof Array === false) {
    return d;
  }
  return _distinct(d).length;
}

/**
 * Join all values of an array into a string. null and undefined are ignored.
 *
 * @version 3.5.7 new
 *
 * @example [["homer", "bart", null, "lisa"]]
 * @example [["homer", "bart"], " / "]
 * @example [[]]
 *
 * @param  {Array}  d          array of values. In a template: `{d.kids[].name:aggStr(' / ')}`
 * @param  {String} separator  [optional] separator, ", " by default
 * @return {String}            joined values
 */
function aggStr (d, separator) {
  if (d instanceof Array === false) {
    return d;
  }
  return d.filter(function (v) {
    return v !== null && typeof v !== 'undefined';
  }).join(_separator(separator));
}

/**
 * Join all distinct values of an array into a string. null and undefined are ignored.
 *
 * @version 3.5.7 new
 *
 * @example [["homer", "bart", "homer"]]
 * @example [["homer", "bart", "homer"], " / "]
 *
 * @param  {Array}  d          array of values. In a template: `{d.kids[].name:aggStrD(' / ')}`
 * @param  {String} separator  [optional] separator, ", " by default
 * @return {String}            joined distinct values
 */
function aggStrD (d, separator) {
  if (d instanceof Array === false) {
    return d;
  }
  return _distinct(d).join(_separator(separator));
}

/**
 * Get the state of a cumulative formatter, for the current report file
 *
 * @private
 */
function _state (context, id, initialValue) {
  if (!context.cumulativeState) {
    context.cumulativeState = Object.create(null);
  }
  if (context.cumulativeState[id] === undefined) {
    context.cumulativeState[id] = initialValue();
  }
  return context.cumulativeState[id];
}

/**
 * Cumulative sum: in a loop, each row prints the sum of the current value and all previous rows.
 * Rows hidden by a filter are not counted. The first parameter is added automatically by Carbone.
 *
 * @version 3.5.7 new
 *
 * @example [10, "id"]
 *
 * @param  {Number} d   value. In a template: `{d.items[i].price:cumSum}`
 * @param  {String} id  unique id of the marker, added by Carbone
 * @return {Number}     running total
 */
function cumSum (d, id) {
  var _acc = _state(this, id, function () {
    return { total : 0 };
  });
  if (this.isRowShown !== false) {
    var _number = _toNumber(d);
    if (_number !== null) {
      _acc.total += _number;
    }
  }
  return _acc.total;
}

/**
 * Cumulative count of distinct values: in a loop, each row prints the number of distinct values found in the current
 * row and all previous rows. Rows hidden by a filter are not counted. The first parameter is added automatically by Carbone.
 *
 * @version 3.5.7 new
 *
 * @example ["a", "id"]
 *
 * @param  {Mixed}   d   value. In a template: `{d.items[i].type:cumCountD}`
 * @param  {String}  id  unique id of the marker, added by Carbone
 * @return {Integer}     number of distinct values
 */
function cumCountD (d, id) {
  var _acc = _state(this, id, function () {
    return new Set();
  });
  if (this.isRowShown !== false && d !== null && typeof d !== 'undefined') {
    _acc.add(_key(d));
  }
  return _acc.size;
}

module.exports = {
  _pluck,
  aggSum,
  aggAvg,
  aggMin,
  aggMax,
  aggCount,
  aggCountD,
  aggStr,
  aggStrD,
  cumSum,
  cumCountD
};
