const NAMED_COLORS = {
  black   : '000000', white   : 'FFFFFF', red     : 'FF0000', green   : '008000', blue    : '0000FF', yellow  : 'FFFF00',
  orange  : 'FFA500', purple  : '800080', gray    : '808080', grey    : '808080', pink    : 'FFC0CB', brown   : 'A52A2A',
  cyan    : '00FFFF', aqua    : '00FFFF', magenta : 'FF00FF', fuchsia : 'FF00FF', lime    : '00FF00', navy    : '000080',
  teal    : '008080', silver  : 'C0C0C0', maroon  : '800000', olive   : '808000'
};

/**
 * Convert a color to an hexadecimal color without "#" (RRGGBB), or null if the color is not valid.
 * Accepted values: `#RRGGBB`, `RRGGBB`, `#RGB`, `rgb(255, 0, 0)` and the basic CSS color names (red, blue, ...).
 *
 * @private
 * @param  {Mixed}  value  color
 * @return {String}        RRGGBB in upper case, null if invalid
 */
function normalizeColor (value) {
  if (typeof value !== 'string') {
    return null;
  }
  var _color = value.trim().toLowerCase();
  if (NAMED_COLORS[_color] !== undefined) {
    return NAMED_COLORS[_color];
  }
  var _rgb = /^rgba?\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*(?:,\s*[\d.]+\s*)?\)$/.exec(_color);
  if (_rgb !== null) {
    return [_rgb[1], _rgb[2], _rgb[3]].map(function (n) {
      return Math.min(parseInt(n, 10), 255).toString(16).padStart(2, '0');
    }).join('').toUpperCase();
  }
  var _hex = /^#?([0-9a-f]{3}|[0-9a-f]{6})$/.exec(_color);
  if (_hex !== null) {
    var _digits = _hex[1].length === 3 ? _hex[1].split('').map(function (c) { return c + c; }).join('') : _hex[1];
    return _digits.toUpperCase();
  }
  return null;
}

/**
 * Change the color of the text or the background of a paragraph, a table cell or a table row. Available for DOCX, ODT and ODS templates, for the
 * cells and the rows of XLSX templates (scopes `cell` and `row`), and for PPTX templates (scopes `p`, `cell`, `row` and `shape`).
 *
 * The marker is analyzed before the data are injected (see lib/color.js), and it is replaced by the color in the attributes
 * of the DOCX XML, or by a style in ODT. The value can be `#RRGGBB`, `RRGGBB`, `#RGB`, `rgb(255, 0, 0)` or a basic color name. If the value is not a valid color,
 * the default color is used. Previous formatters are kept, so a color can be computed with conditional formatters.
 * This function is only called if the marker is not inside a paragraph, a cell or a row of a DOCX or ODT template, it throws an error.
 *
 * Scopes: `p` (paragraph), `cell` (table cell), `row` (table row). Types: `text`, `background`.
 *
 * @version 3.5.7 new
 * @example ["{d.color:color(p, text)}", "p", "text"]
 * @example ["{d.color:color(cell, background)}", "cell", "background"]
 *
 * @param  {String} d      color
 * @param  {String} scope  `p`, `cell` or `row`
 * @param  {String} type   `text` or `background`
 * @return {String}        never returns, it throws an error
 */
function color (d, scope, type) {
  throw new Error('Formatter "color(' + (scope || '') + ', ' + (type || '') + ')" is only available for docx, odt, ods, odp, xlsx and pptx templates, and it must be inside a paragraph (p), a table cell (cell), a table row (row) or a shape (shape, only for pptx). Scopes: p, cell, row, shape. Types: text, background');
}

/**
 * Internal formatter, generated by Carbone to print a color in the XML attributes of a DOCX file
 *
 * @private
 * @param  {String} d  color
 * @return {String}    RRGGBB, or "auto" (default color) if the value is not valid
 */
function _color (d) {
  return normalizeColor(d) || 'auto';
}

/**
 * Internal formatter, generated by Carbone for ODF files (ODT). The color is registered, and a temporary identifier is printed in
 * the style name of the paragraph or the cell. A style which contains this color is created after all data are injected (see lib/color.js).
 *
 * @private
 * @param  {String} d     color
 * @param  {String} kind  `text` or `background`
 * @return {String}       identifier
 */
function _odfColor (d, kind) {
  if (!this.odfColors) {
    this.odfColors = [];
  }
  this.odfColors.push({ kind : kind, color : normalizeColor(d) });
  return 'CARBONE_ODC_' + (this.odfColors.length - 1);
}

/**
 * Internal formatter, generated by Carbone for XLSX files. The color is registered, and a temporary identifier is printed in the
 * style index of the cell. A style which contains this color is created after all data are injected (see lib/color.js).
 *
 * @private
 * @param  {String} d     color
 * @param  {String} kind  `text` or `background`
 * @return {String}       identifier
 */
function _xlsxColor (d, kind) {
  if (!this.xlsxColors) {
    this.xlsxColors = [];
  }
  this.xlsxColors.push({ kind : kind, color : normalizeColor(d) });
  return 'CARBONE_XC_' + (this.xlsxColors.length - 1);
}

/**
 * Internal formatter, generated by Carbone for PPTX files. It prints the color, or an identifier if the color is not valid: the
 * original fill of the template is put back after all data are injected (see lib/color.js).
 *
 * @private
 * @param  {String} d   color
 * @param  {String} id  index of the original fill, saved before the parsing of the template
 * @return {String}     RRGGBB or identifier
 */
function _pptxColor (d, id) {
  return normalizeColor(d) || ('CARBONE_PC_' + id);
}

// executed at the end of the formatters chain, even after show/elseShow which stop the propagation of formatters.
// The value is always a safe color (RRGGBB or auto) or an identifier, so it can be inserted in XML attributes
_color.canInjectXML = true;
_odfColor.canInjectXML = true;
_xlsxColor.canInjectXML = true;
_pptxColor.canInjectXML = true;

module.exports = {
  normalizeColor,
  color,
  _color,
  _odfColor,
  _xlsxColor,
  _pptxColor
};
