const FIT_MODES = ['contain', 'fillwidth', 'fill'];

/**
 * Choose how a dynamic image is resized in the placeholder image of the template.
 *
 * - `contain` (default): the whole image is visible, the ratio is kept, and the image fits in the placeholder
 * - `fillWidth`: the width of the placeholder is used, the ratio is kept, so the height can change
 * - `fill`: the image is stretched to the size of the placeholder
 *
 * The dynamic image is defined by the marker in the alternative text (description) of a picture of the template (DOCX),
 * the value is a public URL (http or https) or a base64 data URI (png, jpeg, gif): `{d.logo:imageFit(fillWidth)}`
 *
 * @version 3.5.7 new
 * @example ["data:image/png;base64,iVBORw0KGgo=", "contain"]
 * @example ["https://example.com/logo.png", "fillWidth"]
 *
 * @param  {String} d     image: URL or base64 data URI
 * @param  {String} mode  `contain`, `fillWidth` or `fill`
 * @return {String}       the image, unchanged
 */
function imageFit (d, mode) {
  var _mode = (mode + '').toLowerCase();
  this.currentImageFit = FIT_MODES.indexOf(_mode) !== -1 ? _mode : 'contain';
  return d;
}

/**
 * Internal formatter, generated by Carbone for the marker of a picture. It registers the image and prints a temporary
 * identifier which is replaced by the image after all data are injected (see lib/image.js).
 *
 * @private
 * @param  {String} d  image: URL or base64 data URI. If it is empty, the picture is removed from the document
 * @return {String}    identifier
 */
function _image (d) {
  var _fit = this.currentImageFit || 'contain';
  this.currentImageFit = undefined;
  if (!this.images) {
    this.images = [];
  }
  if (typeof d !== 'string' || d.trim() === '') {
    return 'CARBONE_IMG_NONE';
  }
  this.images.push({ source : d.trim(), fit : _fit });
  return 'CARBONE_IMG_' + (this.images.length - 1);
}

// executed at the end of the formatters chain, even after show/elseShow. The result is always safe in XML attributes.
_image.canInjectXML = true;

module.exports = {
  imageFit,
  _image
};
