// schemes accepted in links. javascript:, data:, vbscript:, file:, ... are refused
const SAFE_SCHEMES = ['http', 'https', 'mailto', 'tel', 'ftp', 'sms'];

/**
 * Is the URL safe to use in a link? URLs without scheme (relative links, anchors) are accepted.
 *
 * @private
 * @param  {String}  url
 * @return {Boolean}
 */
function isSafeUrl (url) {
  // control characters and spaces are ignored by some readers: "java\nscript:" is "javascript:"
  var _scheme = /^([a-z][a-z0-9+.-]*):/.exec(url.replace(/[\u0000- ]/g, '').toLowerCase());
  return _scheme === null || SAFE_SCHEMES.indexOf(_scheme[1]) !== -1;
}

function buildUrl (d, prefix, suffix) {
  if (d === null || typeof d === 'undefined' || d === '') {
    return '';
  }
  var _url = (prefix || '') + d + (suffix || '');
  return isSafeUrl(_url) ? _url : '';
}

/**
 * Internal formatter, generated by Carbone for links of ODF files (`xlink:href="{d.url}"`)
 *
 * It prints the URL, or nothing if the scheme is not safe (only http, https, mailto, tel, ftp and sms are accepted)
 *
 * @private
 * @param  {String} d       URL
 * @param  {String} prefix  [optional] static text before the URL in the template
 * @param  {String} suffix  [optional] static text after the URL in the template
 * @return {String}         URL, or an empty string
 */
function _link (d, prefix, suffix) {
  return buildUrl(d, prefix, suffix);
}

/**
 * Internal formatter, generated by Carbone for hyperlinks of DOCX and PPTX files. The URL is registered and a temporary
 * identifier is printed. It is replaced by a relationship after all data are injected (see lib/link.js).
 *
 * @private
 * @param  {String} d       URL
 * @param  {String} prefix  [optional] static text before the URL in the template
 * @param  {String} suffix  [optional] static text after the URL in the template
 * @return {String}         identifier
 */
function _hyperlink (d, prefix, suffix) {
  // always created: tokens are replaced at the end only if the list exists, even if all links are invalid
  if (!this.links) {
    this.links = [];
  }
  var _url = buildUrl(d, prefix, suffix);
  if (_url === '') {
    return 'CARBONE_LINK_NONE';
  }
  this.links.push(_url);
  return 'CARBONE_LINK_' + (this.links.length - 1);
}

// executed at the end of the formatters chain, even after show/elseShow
_link.canInjectXML = true;
_hyperlink.canInjectXML = true;

module.exports = {
  isSafeUrl,
  _link,
  _hyperlink
};
